name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  RUSTUP_TOOLCHAIN: nightly

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install nightly toolchain
        run: rustup toolchain install nightly --profile minimal

      - uses: Swatinem/rust-cache@v2
      - name: cargo check
        run: cargo check --no-default-features --features ci

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install nightly toolchain
        run: rustup toolchain install nightly --profile minimal

      - uses: Swatinem/rust-cache@v2
      - name: cargo test
        run: cargo test --lib --no-default-features --features ci

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install nightly toolchain
        run: rustup toolchain install nightly --profile minimal -c clippy

      - uses: Swatinem/rust-cache@v2
      - name: cargo clippy
        run: cargo clippy --no-default-features --features ci

  fmt:
    name: Format
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Install nightly toolchain
        run: rustup toolchain install nightly --profile minimal -c rustfmt

      - name: cargo fmt
        run: cargo fmt -- --check
